# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/pixles-docs"
    schedule:
      interval: "weekly"
  - package-ecosystem: "bun"
    directory: "/pixles-web"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/pixles-api"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/pixles-api"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker-compose"
    directory: "/pixles-api"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "swift"
    directory: "/pixles-swift"
    schedule:
      interval: "weekly"
