# Enforces consistent code style
edition = "2021"                         # Use latest Rust edition
max_width = 100                          # Line length limit
tab_spaces = 4                           # Indentation size
newline_style = "Unix"                   # Consistent line endings

# Code organization
reorder_imports = true                   # Sort imports alphabetically
imports_granularity = "Module"           # Group imports by module
group_imports = "StdExternalCrate"       # Group imports by std/external/crate

# Formatting strictness
format_code_in_doc_comments = true       # Format code in documentation
format_macro_matchers = true             # Format macro patterns
format_macro_bodies = true               # Format macro bodies
format_strings = true                    # Format string literals
wrap_comments = true                     # Wrap comments at max_width

# Error control
error_on_line_overflow = true            # Error on lines exceeding max_width
error_on_unformatted = true              # Error if unable to format something

# Specific formatting choices
use_field_init_shorthand = true          # Use field init shorthand when possible
use_try_shorthand = true                 # Use try (?) shorthand
binop_separator = "Front"                # Put operators at the beginning of lines
control_brace_style = "AlwaysNextLine"   # Braces always on next line for control flow
fn_args_layout = "Tall"                  # One argument per line when wrapping
where_single_line = false                # Always put where clauses on multiple lines
trailing_semicolon = false               # Remove unnecessary trailing semicolons

# TODO: Review ^^
