[package]
name = "pixles-api-entity"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
name = "entity"
path = "src/lib.rs"

[dependencies]
chrono = { workspace = true }
nanoid = { workspace = true }
serde = { workspace = true }
sea-orm = { workspace = true }
