FROM rust:bookworm as build-env
RUN apt update && apt upgrade -y && apt install -y protobuf-compiler libprotobuf-dev
WORKDIR /app
COPY . /app
RUN cargo build --release

FROM gcr.io/distroless/cc-debian12
COPY --from=build-env /app/target/release/pixles-api /
EXPOSE 3000
CMD ["./pixles-api"]
# TODO: sql dependencies are failing to execute in distroless image
#  TODO: Separate different images based on features
