FROM rust:1 as build-env
WORKDIR /app
COPY . /app
RUN cargo build --release

FROM gcr.io/distroless/cc-debian12
COPY --from=build-env /app/target/release/pixles-api /
EXPOSE 3000
CMD ["./pixles-api"]
# TODO: sql dependencies are failing to execute in distroless image
