#[cfg(feature = "auth")]
pub const ACCESS_TOKEN_EXPIRY: u64 = 60 * 15; // 15 minutes
#[cfg(feature = "auth")]
pub const REFRESH_TOKEN_EXPIRY: u64 = 60 * 60 * 24 * 7; // 7 days
#[cfg(feature = "auth")]
pub const TOTP_ISSUER: &str = "Capsule";
#[cfg(feature = "auth")]
pub const MAX_PASSKEYS_PER_USER: usize = 10;
#[cfg(feature = "auth")]
pub const MAX_FAILED_LOGIN_ATTEMPTS: i32 = 10;
#[cfg(feature = "auth")]
pub const RATE_LIMIT_LOGIN_MAX: i64 = 10;
#[cfg(feature = "auth")]
pub const RATE_LIMIT_LOGIN_WINDOW_SECS: u64 = 60;
#[cfg(feature = "auth")]
pub const RATE_LIMIT_REGISTER_MAX: i64 = 10;
#[cfg(feature = "auth")]
pub const RATE_LIMIT_REGISTER_WINDOW_SECS: u64 = 60;
#[cfg(feature = "auth")]
pub const RATE_LIMIT_PASSWORD_RESET_MAX: i64 = 5;
#[cfg(feature = "auth")]
pub const RATE_LIMIT_PASSWORD_RESET_WINDOW_SECS: u64 = 60;

#[cfg(feature = "upload")]
pub const MAX_FILE_SIZE: usize = 32 * 1024 * 1024 * 1024; // 32 GiB
#[cfg(feature = "upload")]
pub const MAX_CACHE_SIZE: usize = 64 * 1024 * 1024 * 1024; // 64 GiB
