use chrono::{DateTime, Utc};
use nanoid::nanoid;
use sea_orm::{Set, entity::prelude::*};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "passkeys")]
pub struct Model {
    /// Unique identifier for this record (e.g., a NanoID or KSUID).
    #[sea_orm(primary_key, column_type = "Char(Some(21))")]
    pub id: String,

    /// The owner of this passkey.
    #[sea_orm(column_type = "Char(Some(21))", indexed)]
    pub user_id: String,

    /// The raw Credential ID generated by the authenticator.
    pub cred_id: Vec<u8>,

    /// The public key used to verify future authentication signatures.
    pub public_key: Vec<u8>,

    /// Signature counter to detect and prevent cloned authenticators.
    pub counter: i64,

    /// A user-defined label for the key (e.g., "Work Laptop" or "Pixel 8").
    pub name: String,

    /// Timestamp when the passkey was first registered.
    #[sea_orm(
        column_type = "TimestampWithTimeZone",
        default_value = "CURRENT_TIMESTAMP"
    )]
    pub created_at: DateTime<Utc>,

    /// The last time this key was successfully used to log in.
    #[sea_orm(column_type = "TimestampWithTimeZone", nullable)]
    pub last_used_at: Option<DateTime<Utc>>,

    /// Authenticator Attestation GUID; identifies the hardware/software type.
    #[sea_orm(column_type = "Uuid", nullable)]
    pub aaguid: Option<Uuid>,

    /// Whether the device is capable of backing up the private key.
    pub backup_eligible: bool,

    /// The current backup status of the credential.
    pub backup_state: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {
    fn new() -> Self {
        Self {
            id: Set(nanoid!()),
            ..ActiveModelTrait::default()
        }
    }
}
