included:
  - BuildTools
  - Pixles
  - PixlesTests
  - PixlesUITests
  - Package.swift

excluded:
  - .build
  - BuildTools/.build

analyzer_rules:
  - unused_declaration
  - unused_import
opt_in_rules:
  - all
disabled_rules:
  - contrasted_opening_brace
  - todo
  # - anonymous_argument_in_multiline_closure
  # - async_without_await
  # - conditional_returns_on_newline
  # - convenience_type
  # - discouraged_optional_collection
  # - explicit_acl
  # - explicit_enum_raw_value
  # - explicit_top_level_acl
  # - explicit_type_interface
  # - file_types_order
  # - force_unwrapping
  # - function_default_parameter_at_end
  # - indentation_width
  # - missing_docs
  # - multiline_arguments
  # - multiline_arguments_brackets
  # - multiline_function_chains
  # - multiline_parameters_brackets
  # - no_extension_access_modifier
  # - no_grouping_extension
  # - no_magic_numbers
  # - one_declaration_per_file
  # - prefer_nimble
  # - prefixed_toplevel_constant
  # - required_deinit
  # - sorted_enum_cases
  # - strict_fileprivate
  # - switch_case_on_newline
  # - trailing_closure
  # - type_contents_order
  # - vertical_whitespace_between_cases
